#!/usr/bin/env bash
#Installing nginx on the server

# Get needed update and install nginX
sudo apt-get -y update
sudo apt-get -y install nginx

#echo Hello World
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location / redirect_me{
        return 301 https://github.com/ibkodus116;
    }
}" > /etc/nginx/sites-available/default
service nginx start
