#!/usr/bin/env bash
#Installing nginx on the server

# Get needed update and install nginX
apt-get -y update
apt-get -y install nginx

#echo Hello World
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ibkodus116 permanent;/" /etc/nginx/sites-available/default
service nginx start
