#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process.
echo $$ > /var/run/myscript.pid

trap "echo 'i hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT

while true
    do
        echo "to infinity and beyond"
        sleep 2
done