#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.
a=0

while [ $a -lt 10 ];
do
    if [ "$a" == 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    a=$(( a + 1 ))
done
