#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.
a=1

while [ $a -lt 21 ];
do
    echo $a

    case $a in
        4)
            echo "bad luck from China"
        ;;
        9)
            echo "bad luck from Japan"
        ;;
        17)
            echo "bad luck from Japan"
        ;;
    esac
    a=$(( a + 1 ))
done
