#!/usr/bin/env bash
# a Bash script that displays Clock.
hour=0

while [ $hour -lt 13 ];
    do
        echo "Hour: $hour"
        min=1
        while [ $min -lt 60 ]
            do
                echo $min
            min=$(( min + 1 ))
        done
    hour=$(( hour + 1 ))
done